spring.application.name=ShopWise

spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:28356/railway
spring.datasource.username=root
spring.datasource.password=MuJnwHJTmWyWoYEYXEUYweVDNDxCbrGJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}